import type { Metadata } from "next";
import { Montserrat, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ModalProvider from "@/components/ModalProvider/modal-provider";

interface RootLayoutProps {
  children: React.ReactNode;
}

const montserrat = Plus_Jakarta_Sans({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Insightfy",
  description: "Generated by create next app",
};

function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-br">
      <body className={montserrat.className}>
        <ModalProvider /> 
        {children}
      </body>
    </html>
  );
}

export default RootLayout;