import type { Metadata } from "next";
import "./globals.css";
import ModalProvider from "@/components/ModalProvider/modal-provider";

interface RootLayoutProps {
  children: React.ReactNode;
}
export const metadata: Metadata = {
  title: "Insightfy",
  description: "Generated by create next app",
};

function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-br">
      <body>
        <ModalProvider /> 
        {children}
      </body>
    </html>
  );
}

export default RootLayout;